-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 00:55:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventsoft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventsoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventsoft` DEFAULT CHARACTER SET utf8 ;
USE `inventsoft` ;

-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `fecha_integracion` DATE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contra` VARCHAR(45) NULL,
  `estado` INT NULL,
  `id_empleado` INT NULL,
  `rang` VARCHAR(3) NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tbl_usuarios_tbl_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_tbl_usuarios_tbl_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `inventsoft`.`tbl_empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tipo_pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_inf_facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_inf_facturacion` (
  `id_inf_facturacion` INT NOT NULL,
  `punto_de_emision` INT NULL,
  `establecimiento` INT NULL,
  `tipo_de_documento` INT NULL,
  `minimo` INT NULL,
  `maximo` INT NULL,
  `fecha_limite_de_emision` DATETIME NULL,
  `id_usuario` INT NULL,
  `CAI` VARCHAR(37) NULL,
  `estado` INT NULL,
  `fecha_de_cambio` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id_inf_facturacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(45) NULL,
  `rtn` VARCHAR(100) NULL,
  `fecha_hora` TIMESTAMP(0) NULL,
  `estado` INT NULL,
  `id_pago` INT NOT NULL,
  `id_inf_facturacion` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_tbl_factura_tipo_pago1_idx` (`id_pago` ASC),
  INDEX `fk_tbl_factura_tbl_inf_facturacion1_idx` (`id_inf_facturacion` ASC),
  INDEX `fk_tbl_factura_tbl_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_factura_tipo_pago1`
    FOREIGN KEY (`id_pago`)
    REFERENCES `inventsoft`.`tipo_pago` (`id_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_inf_facturacion1`
    FOREIGN KEY (`id_inf_facturacion`)
    REFERENCES `inventsoft`.`tbl_inf_facturacion` (`id_inf_facturacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factura_tbl_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `inventsoft`.`tbl_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `estado` INT NULL,
  `fecha_inclucion` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cod` VARCHAR(45) NULL,
  `precio_compra` DOUBLE NULL,
  `precio_venta` DOUBLE NULL,
  `isv` INT NULL,
  `id_categoria` INT NOT NULL,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_tbl_producto_tbl_categoria1_idx` (`id_categoria` ASC),
  INDEX `fk_tbl_producto_tbl_proveedor1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_tbl_producto_tbl_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `inventsoft`.`tbl_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_producto_tbl_proveedor1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `inventsoft`.`tbl_proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_factdetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_factdetalle` (
  `id_factdetalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `id_producto` INT NOT NULL,
  `id_factura` INT NOT NULL,
  PRIMARY KEY (`id_factdetalle`),
  INDEX `fk_tbl_factdetalle_tbl_producto1_idx` (`id_producto` ASC),
  INDEX `fk_tbl_factdetalle_tbl_factura1_idx` (`id_factura` ASC),
  CONSTRAINT `fk_tbl_factdetalle_tbl_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventsoft`.`tbl_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_factdetalle_tbl_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `inventsoft`.`tbl_factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `cantidad_existente` INT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_tbl_stock_tbl_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_tbl_stock_tbl_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `inventsoft`.`tbl_producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_accesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_accesos` (
  `id_accesos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `acesso_reportes` INT NULL,
  `actualizar_pro` INT NULL,
  `crear_empleado` INT NULL,
  `crear_usuario` INT NULL,
  `crear_venta` INT NULL,
  `crear_compra` INT NULL,
  `crear_producto` INT NULL,
  PRIMARY KEY (`id_accesos`),
  INDEX `fk_tbl_accesos_tbl_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_accesos_tbl_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `inventsoft`.`tbl_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_bitacora` (
  `id_bitacora` INT NOT NULL,
  `id_usuario` INT NULL,
  `accion` VARCHAR(500) NULL,
  `fecha_hora` TIMESTAMP(0) NULL,
  PRIMARY KEY (`id_bitacora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `tbl_compra_fecha` TIMESTAMP(0) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_tbl_compra_tbl_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_tbl_compra_tbl_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `inventsoft`.`tbl_usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_compradet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_compradet` (
  `id_compradet` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL,
  `id_proveedor` INT NULL,
  `cantidad` VARCHAR(45) NULL,
  `id_compra` INT NOT NULL,
  PRIMARY KEY (`id_compradet`),
  INDEX `fk_tbl_compradet_tbl_compra1_idx` (`id_compra` ASC),
  CONSTRAINT `fk_tbl_compradet_tbl_compra1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `inventsoft`.`tbl_compra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventsoft`.`tbl_stockdetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventsoft`.`tbl_stockdetalle` (
  `id_stockdetalle` INT NOT NULL AUTO_INCREMENT,
  `transaccion` VARCHAR(50) NULL,
  `fecha_mod` TIMESTAMP(0) NULL,
  `id_stock` INT NOT NULL,
  PRIMARY KEY (`id_stockdetalle`),
  INDEX `fk_tbl_stockdetalle_tbl_stock1_idx` (`id_stock` ASC),
  CONSTRAINT `fk_tbl_stockdetalle_tbl_stock1`
    FOREIGN KEY (`id_stock`)
    REFERENCES `inventsoft`.`tbl_stock` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
